### ISSUE TITLE
generation migration not possible with getenv in settings

### ISSUE THREAD

**Issue by beni92** [beni92/SAM#1]
Hei,

when using 
`'database' => [
        'adapter'     => 'Mysql',
        'host'        => getenv('MYSQL_HOST'),
        'username'    => getenv('MYSQL_USER'),
        'password'    => getenv('MYSQL_PASSWORD'),
        'dbname'      => getenv('MYSQL_DATABASE'),
        'charset'     => 'utf8',
    ],`

in the settings the migration is not working. The migration tool throws an error
ERROR: SQLSTATE[HY000] [2002] No such file or directory

when generating the migration with specific elements the generation works.
`'database' => [
        'adapter'     => 'Mysql',
        'host'        => "localhost:13306",
        'username'    => "root",
        'password'    => "root",
        'dbname'      => "phalcon",
        'charset'     => 'utf8',
    ],`

http://stackoverflow.com/questions/30472732/phalcon-sqlstatehy000-2002-no-such-file-or-directory#comment49085103_30472732

**Comment by amq** [comment]
Does this help?
```
docker run -it --rm \
--env-file dev.env \
--network=$(docker network ls -f "name=sam_default" -q) \
-v $(pwd)/server:/app \
amqamq/phalcon \
phalcon migration generate
```

upd: overlooked "generation"

**Comment by beni92** [comment]
The problem is not running the migration but generating the migration

I try if it works from the machine:
```
docker run -it --rm \
--env-file dev.env \
--network=$(docker network ls -f "name=sam_default" -q) \
-v $(pwd)/server:/app \
amqamq/phalcon \
phalcon migration --action generate
```

worked fine.
